app/config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :users , only: [:new, :create, :destroy, :index]

  root to: 'login#index'

  resources :items
  resources :likes
  resources :dislikes


  resources :matches do
    resources :messages
  end

  resources :conversations do
    resources :messages
  end
end

app/app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/app/models/dislike.rb
class Dislike < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessor :test
  belongs_to :user, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  has_many :matches, foreign_key: "item_offered_id", dependent: :destroy
  mount_uploader :picture_url, ImageUploader
  public

  def self.test
    items = Item.all

    items.each{|item|
      item.remote_picture_url_url = item.url
      item.save
    }
  end
  def get_all_item_matches
    result_id = []
    item_matches = Match.where("item_offered_id = ? or item_liked_id = ?", self.id, self.id)
    item_matches.each do |item|
      if item.item_offered_id == self.id
        result_id << item.item_liked_id
      else
        result_id << item.item_offered_id
      end
    end
    Item.find(result_id)
  end
  #gets all the items that have liked this item
  def get_all_potential_trades
    result = Like.where("item_liked_id = ?", self.id).pluck(:item_offered_id)
    potential = Item.find(result)
  end
end

app/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :item_offered, :class_name => 'Item'
  belongs_to :item_liked, :class_name => 'Item'
  after_save :check_matches

  def check_matches
    #search likes for inverse of item ids
    result = Like.where(:item_offered=>self.item_liked).where(:item_liked=>self.item_offered)
    #if results > 0, then insert a match in the matches table
    Match.create(item_offered: self.item_offered, item_liked: self.item_liked, user_offered: self.item_offered.user, user_liked: self.item_liked.user) if result.length > 0
  end
end

app/app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :user_offered, :class_name => 'User'
  belongs_to :user_liked, :class_name => 'User'
  belongs_to :item_offered, :class_name => 'Item'
  belongs_to :item_liked, :class_name => 'Item'
end

app/app/models/message.rb
class Message < ActiveRecord::Base
 belongs_to :conversation
 belongs_to :user
 validates_presence_of :body, :conversation_id, :user_id
 def message_time
  created_at.strftime("%m/%d/%y at %l:%M %p")
 end
end

app/app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :ip_address

  has_many :items
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  has_many :liked_items, through: :likes, class_name: 'Item', source: :item
  has_many :disliked_items, through: :dislikes, class_name: 'Item', source: :item
  has_many :conversations, :foreign_key => :sender_id  # has_many :sender, foreign_key: 'user_sender_id', :class_name => 'Message'
  # has_many :receiver, foreign_key: 'user_receiver_id', :class_name => 'Message'
  geocoded_by :ip_address   # can also be an IP address
  after_validation :geocode

  def self.from_omniauth(auth)
    where(uid: auth.uid).first_or_create do |user|
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.email    = auth.info.email
      user.picture_profile_url = auth.info.image
      user.save
    end
  end

  def get_all_user_items
    myItems = Item.where(:user_id=>self.id)
    myItems
  end
  # Displays the conversations with the matched users
  def get_all_user_conversations
    contacts_part_one = Match.where("user_liked_id = ?", self.id).pluck(:user_offered_id)
    contacts_part_two = Match.where("user_offered_id = ?", self.id).pluck(:user_liked_id)
    a = User.find(contacts_part_one)
    b = User.find(contacts_part_two)
    c = a + b
    c
  end
  def get_nearby_items(distance)
    d = distance.to_i * 400
    items_near_me = []
    users_near_me = self.nearbys(d).shuffle
    users_near_me.each do |user|
      items_near_me << Item.where('user_id = ?', user.id).first
    end
    items_near_me
  end
  def get_all_messages_by_user(user)
    user1_id = self.id
    user2_id = user.id
    Message.where('(user_sender_id = ? and user_receiver_id = ?) or
    (user_sender_id = ? and user_receiver_id = ?)', user1_id,user2_id,user2_id,user1_id).order('created_at')
  end

end

app/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :json, :html
  def index
   if current_user
     if params[:filter] == '1'
       @item = Item.where('user_id <> ? ', current_user.id)
     elsif params[:filter] == '2'
       @item = current_user.get_nearby_items(params[:distance])
     end
     respond_with(@item)
   else
     redirect_to root_url
   end
 end
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to :back
    end
  end
  def show
    redirect_to items_path
  end
  def item_params
    params.require(:item).permit(:name, :picture_url, :description, :user_id, :remote_picture_url_url)
  end
end

app/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  respond_to :json, :html


  def create
    @like = Like.new({item_offered_id: params['item_offered_id'], item_liked_id: params['item_liked_id']})
    if @like.save
      render json: @like.check_matches
    end
  end

  def show
    redirect_to items_path
  end

  def like_params
    params.require(:like).permit(:item_offered_id, :item_liked_id)
  end
end

app/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    # if current_user
    #   redirect_to items_path
    # else
    #    redirect_to root_path
    # end
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/items_helper.rb
module ItemsHelper
end

app/app/helpers/login_helper.rb
module LoginHelper
end

app/app/helpers/matches_helper.rb
module MatchesHelper
end

app/app/helpers/messages_helper.rb
module MessagesHelper
end

app/app/helpers/pages_helper.rb
module PagesHelper
end

app/app/helpers/sessions_helper.rb
module SessionsHelper
end

app/app/helpers/swipe_helper.rb
module SwipeHelper
end

app/app/helpers/user_helper.rb
module UserHelper
end

app/app/helpers/users_helper.rb
module UsersHelper
end

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section class="hero is-danger is-left is-bold" style="margin-top:-70px">
    <div class="hero-header">
      <header class="header">
        <div class="container">
          <div class="header-left">
            <h1 class="title">BARTR</h1>
            <h2 class="subtitle my-subtitle" style="margin-top: 8px">Trade Stuff, <strong>locally</strong> and <strong>fast!</strong></h2>
          </div>
          <span id="header-toggle" class="header-toggle">
            <span></span>
            <span></span>
            <span></span>
          </span>
          <div class="header-right header-menu">
            <% if current_user %>
            Signed in as <strong> &nbsp;<%= current_user.name %>! &nbsp;</strong>
            <%= link_to "Sign out", signout_path, id: "sign_out" %>
            <% else %>
            <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
            <% end %>
          </div>
        </div>
      </header>
    </div>

    <div class="hero-footer">
      <nav class="tabs is-boxed">
        <div class="container">
          <div class="tabs">
            <ul>
              <li class="tab1">
                <%= link_to 'Find Stuff', items_path%>
              </li>
              <li class="tab2">
                <a href="/matches">Matches</a>
              </li>
              <li class="tab3">
                <a href="/conversations">Messages</a>
              </li >
              <!-- <li class="tab4">
                <%= link_to 'My Profile', users_path%>
              </li> -->
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </section>

  <div class="modal">
    <div class="modal-background"></div>
    <div class="modal-container">
      <div class="modal-content">
        <div class="box">
          <article class="media">
            <div class="media-left">
              <figure class="image is-64x64">
                <img src="/images/fb-art.jpg" alt="Image">
              </figure>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <div id="loginform">
                    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
                  </p>
                </div>
                <nav class="navbar">
                  <div class="navbar-left">
                    <a class="navbar-item">
                      <span class="icon is-small"><i class="fa fa-reply"></i></span>
                    </a>
                    <a class="navbar-item">
                      <span class="icon is-small"><i class="fa fa-retweet"></i></span>
                    </a>
                    <a class="navbar-item">
                      <span class="icon is-small"><i class="fa fa-heart"></i></span>
                    </a>
                  </div>
                </nav>
              </div>
            </article>
          </div>
        </div>
      </div>

    </div>

    <%= yield %>

  </body>
  </html>

app/app/views/layouts/template.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="bulma.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="bulma.min.css">
    <meta charset="utf-8">
    <title>Bulma Test/Template</title>
  </head>
  <body> 
    <section class="hero is-info is-left is-bold">
      <div class="hero-content">
        <div class="container">
          <p class="title">
            BINDER
          </p>
          <p class="subtitle">
            Trade Stuff, locally and fast.
          </p>
        </div>
      </div>

      <div class="hero-footer">
        <nav class="tabs is-boxed">
          <div class="container">
            <ul>
              <li>
                <a href="/documentation/overview/">Find Stuff</a>
              </li>
              <li>
                <a href="/documentation/modifiers/syntax">My Items</a>
              </li>
              <li>
                <a href="/documentation/grid/">My Matches</a>
              </li>
              <li class="is-active">
                <a href="/documentation/navbar/">My Profile</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </section>
    <section class="section is-medium">
      <div class="container">
        <h3 class="title is-2">
          <a>
            Latest Item
          </a>
        </h3>

        <div class="columns">
          <div class="column is-third">
            <div class="card">
              <figure class="card-image is-4x3">
                <img src="http://placehold.it/300x225" alt="">
              </figure>
              <div class="card-content">
                <div class="media">
                  <div class="media-left">
                    <figure class="image is-32x32">
                      <img src="http://placehold.it/64x64" alt="Image">
                    </figure>
                  </div>
                  <div class="media-content">
                    <p class="title is-5">Card</p>
                    <p class="subtitle is-6">Subtitle</p>
                  </div>
                </div>

                <div class="content">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec iaculis mauris. <a href="#">@bulmaio</a>. <a href="#">#css</a> <a href="#">#responsive</a>
                  <br>
                  <small>11:09 PM - 1 Jan 2016</small>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <title>Geolocation</title>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <style>
  html, body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
  #map {
    height: 50%;
  }
  </style>
</head>
<body>
  <div id="map"></div>
  <div>
    <h1>LOCATION WORKS!</h1>
    
  </div>

  <fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button>
<fb:logout-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:logout-button>

<div id="status">
</div>
<div
data-show-faces="true">
</div>
</body>
</html>