app/config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :users , only: [:new, :create, :destroy, :index]

  root to: 'login#index'

  resources :items
  resources :likes
  resources :dislikes


  resources :matches do
    resources :messages
  end

  resources :conversations do
    resources :messages
  end
end

app/app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/app/models/dislike.rb
class Dislike < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessor :test
  belongs_to :user, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  has_many :matches, foreign_key: "item_offered_id", dependent: :destroy
  mount_uploader :picture_url, ImageUploader
  public

  def self.test
    items = Item.all

    items.each{|item|
      item.remote_picture_url_url = item.url
      item.save
    }
  end
  def get_all_item_matches
    result_id = []
    item_matches = Match.where("item_offered_id = ? or item_liked_id = ?", self.id, self.id)
    item_matches.each do |item|
      if item.item_offered_id == self.id
        result_id << item.item_liked_id
      else
        result_id << item.item_offered_id
      end
    end
    Item.find(result_id)
  end
  #gets all the items that have liked this item
  def get_all_potential_trades
    result = Like.where("item_liked_id = ?", self.id).pluck(:item_offered_id)
    potential = Item.find(result)
  end
end

app/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :item_offered, :class_name => 'Item'
  belongs_to :item_liked, :class_name => 'Item'
  after_save :check_matches

  def check_matches
    #search likes for inverse of item ids
    result = Like.where(:item_offered=>self.item_liked).where(:item_liked=>self.item_offered)
    #if results > 0, then insert a match in the matches table
    Match.create(item_offered: self.item_offered, item_liked: self.item_liked, user_offered: self.item_offered.user, user_liked: self.item_liked.user) if result.length > 0
  end
end

app/app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :user_offered, :class_name => 'User'
  belongs_to :user_liked, :class_name => 'User'
  belongs_to :item_offered, :class_name => 'Item'
  belongs_to :item_liked, :class_name => 'Item'
end

app/app/models/message.rb
class Message < ActiveRecord::Base
 belongs_to :conversation
 belongs_to :user
 validates_presence_of :body, :conversation_id, :user_id
 def message_time
  created_at.strftime("%m/%d/%y at %l:%M %p")
 end
end

app/app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :ip_address

  has_many :items
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  has_many :liked_items, through: :likes, class_name: 'Item', source: :item
  has_many :disliked_items, through: :dislikes, class_name: 'Item', source: :item
  has_many :conversations, :foreign_key => :sender_id  # has_many :sender, foreign_key: 'user_sender_id', :class_name => 'Message'
  # has_many :receiver, foreign_key: 'user_receiver_id', :class_name => 'Message'
  geocoded_by :ip_address   # can also be an IP address
  after_validation :geocode

  def self.from_omniauth(auth)
    where(uid: auth.uid).first_or_create do |user|
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.email    = auth.info.email
      user.picture_profile_url = auth.info.image
      user.save
    end
  end

  def get_all_user_items
    myItems = Item.where(:user_id=>self.id)
    myItems
  end
  # Displays the conversations with the matched users
  def get_all_user_conversations
    contacts_part_one = Match.where("user_liked_id = ?", self.id).pluck(:user_offered_id)
    contacts_part_two = Match.where("user_offered_id = ?", self.id).pluck(:user_liked_id)
    a = User.find(contacts_part_one)
    b = User.find(contacts_part_two)
    c = a + b
    c
  end
  def get_nearby_items(distance)
    d = distance.to_i * 400
    items_near_me = []
    users_near_me = self.nearbys(d).shuffle
    users_near_me.each do |user|
      items_near_me << Item.where('user_id = ?', user.id).first
    end
    items_near_me
  end
  def get_all_messages_by_user(user)
    user1_id = self.id
    user2_id = user.id
    Message.where('(user_sender_id = ? and user_receiver_id = ?) or
    (user_sender_id = ? and user_receiver_id = ?)', user1_id,user2_id,user2_id,user1_id).order('created_at')
  end

end

app/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :json, :html
  def index
   if current_user
     if params[:filter] == '1'
       @item = Item.where('user_id <> ? ', current_user.id)
     elsif params[:filter] == '2'
       @item = current_user.get_nearby_items(params[:distance])
     end
     respond_with(@item)
   else
     redirect_to root_url
   end
 end
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to :back
    end
  end
  def show
    redirect_to items_path
  end
  def item_params
    params.require(:item).permit(:name, :picture_url, :description, :user_id, :remote_picture_url_url)
  end
end

app/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  respond_to :json, :html


  def create
    @like = Like.new({item_offered_id: params['item_offered_id'], item_liked_id: params['item_liked_id']})
    if @like.save
      render json: @like.check_matches
    end
  end

  def show
    redirect_to items_path
  end

  def like_params
    params.require(:like).permit(:item_offered_id, :item_liked_id)
  end
end

app/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    # if current_user
    #   redirect_to items_path
    # else
    #    redirect_to root_path
    # end
  end
end

app/app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @users = current_user.get_all_user_conversations
    @items = current_user.get_all_user_items
    @conversations = Conversation.all
  end
  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],
      params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end
  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/app/controllers/swipe_controller.rb
class SwipeController < ApplicationController
  def findstuff
    @items = current_user.get_all_user_items
    @otheritems = Item.all - current_user.get_all_user_items
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/items_helper.rb
module ItemsHelper
end

app/app/helpers/login_helper.rb
module LoginHelper
end

app/app/helpers/matches_helper.rb
module MatchesHelper
end

app/app/helpers/messages_helper.rb
module MessagesHelper
end

app/app/helpers/pages_helper.rb
module PagesHelper
end

app/app/helpers/sessions_helper.rb
module SessionsHelper
end

app/app/helpers/swipe_helper.rb
module SwipeHelper
end

app/app/helpers/user_helper.rb
module UserHelper
end

app/app/helpers/users_helper.rb
module UsersHelper
end

app/app/views/matches/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <title>Mailbox / Matches</title>

  <script type="text/javascript">
  $( document ).ready(function() {
    $(".tab2").addClass('is-active');
  });
  </script>

</head>

<body>

  <section>
    <div class="container">
      <h2 class="subtitle is-2"><i class="fa fa-users"></i> Matches</h2>
      <div class="columns">
        <div class="column">
          <% @items.each do |item| %>
          <h2 style="margin-top: 30px" class="subtitle is-4"><i class="fa fa-user-plus"></i> <%=item.name%></h2>

          <h2 style="margin-bottom: 10px" <i class="image is-128x128"> <img src="<%=item.picture_url.thumb.url %>"></i></span><%= item.name%> </h2>
          <%matches = item.get_all_item_matches%>
          <%matches.each do |match|%>
          <%user = User.find(match.user_id) %>
          <!-- <div class="notification is-primary">
          <div class="media">
          <div class="media-left">
          <img class="image is-64x64" src='<%=match.url%>' alt="Image">
        </div>
        <div class="media-left">
        <p>
        <strong><%= user.name %></strong>
        <br>
        <%=match.name%>
      </p>
      <!-- </div>
      <div class="media-left"> -->
      <!-- <%= link_to conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post' do %> -->
      <!-- <span class="icon is-medium"><i class="fa fa-envelope"></i></span>
      <% end %>
    </a>
  </div>
</div>
</div> -->
<div class="card">
  <div class="card-image">
    <figure class="image is-4by3">
      <img class="image is-64x64" src='<%=match.url%>' alt="Image">
    </figure>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-32x32">
          <img src="http://placehold.it/64x64" alt="Image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-5"><strong><%= user.name %></strong></p>
        <p class="subtitle is-6"><strong><%= match.name %></strong></p>
      </div>
    </div>

    <div class="content">
      <strong><%= match.description %></strong>
      <br>
      <small>11:09 PM - 1 Jan 2016</small>
    </div><div class="media-left">
    <%= link_to conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post' do %>
    <span class="icon is-medium"><i class="fa fa-envelope"></i></span>
    <% end %>
  </a>
</div>
  </div>
</div>
<% end %>
<% end %>
</div>

</div>
</div>
</section>




</body>